---
- name: Basic playbook
  hosts: local
  become: true
  
  vars:
    name1: "Ashok"
    name2: "Prasanna"
    name3: "Lakshya"
    name4: "Varsha"
  tasks:
     - name : Print Message
       debug :
         msg:
           - "Name value is {{ name1 }}"
           - "Name value is {{ name2 }}"
           - "Name value is {{ name3 }}"
           - "Name value is {{ name4 }}"
